### ISSUE TITLE
`ypdf-writer-1.3.5.gem` dependencies

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ypdf-writer#3]
1. Doing a `bundle install` for `ydim`
2. Results in
3. `Downloading ypdf-writer-1.3.5 revealed dependencies not in the API or the lockfile (rexml (>= 0), rmagick (>= 0), hpricot (>= 0)).
Either installing with `--full-index` or running `bundle update ypdf-writer` should fix the problem.`

**Comment by ngiger** [comment]
Woher hast Du das? Mit welcher Ruby-Version
```
egrep 'rexml|rmagick|hpricot' Gemfile* ypdf-writer.gemspec 
Gemfile.lock:      hpricot
Gemfile.lock:      rexml
Gemfile.lock:      rmagick
Gemfile.lock:    hpricot (0.8.6)
Gemfile.lock:    rexml (3.2.5)
Gemfile.lock:    rmagick (5.1.0)
ypdf-writer.gemspec:  s.add_dependency('rexml')
ypdf-writer.gemspec:  s.add_dependency('rmagick')
ypdf-writer.gemspec:  s.add_dependency('hpricot')
```

**Comment by zdavatz** [comment]
`bundle install` for `ydim-html` works now.
